---
- name: Delete keycloak secrets
  k8s_v1_secret:
    name: '{{ item }}'
    namespace: '{{ namespace }}'
    state: absent
  with_items:
  - keycloak

- name: Delete config maps
  k8s_v1_config_map:
    name: '{{ item }}'
    namespace: '{{ namespace }}'
    state: absent
  with_items:
  - keycloak