- name: delete route
  openshift_v1_route:
    name: keycloak
    namespace: '{{ namespace }}'
    state: absent

- name: delete service
  k8s_v1_service:
    name: keycloak
    namespace: '{{ namespace }}'
    state: absent

- name: delete deployment config
  openshift_v1_deployment_config:
    name: keycloak
    namespace: '{{ namespace }}'
    state: absent

- 
  name: delete secrets
  command: oc delete secret {{ item }}
  with_items:
    - keycloak

