---
- name: get tag
  shell: echo '{{ _apb_provision_creds.URI }}' | cut -f2 -d'-'
  register: tag_out

- set_fact:
    TAG: "{{ tag_out.stdout }}"
    
- set_fact:
    keycloak_service_name: keycloak-{{ TAG }}
    postgres_service_name: postgres-{{ TAG }}
    keycloak_route_name: keycloak-{{ TAG }}
    keycloak_configmap_name: keycloak-{{ TAG }}
    keycloak_secret_name: keycloak-{{ TAG }}
    postgres_secret_name: keycloak-postgres-{{ TAG }}
    keycloak_pv_claim_name: keycloak-metrics-{{ TAG }}
    postgres_pv_claim_name: postgres-{{ TAG }}

- block:
  - include_tasks: deprovision-keycloak.yml
    when: USE_SHARED_SERVICE is undefined or
          not USE_SHARED_SERVICE
  - include_tasks: cleanup-keycloak.yml
    when:
      - USE_SHARED_SERVICE is defined
      - USE_SHARED_SERVICE
  always:
  - include_tasks: cleanup-resources.yml