- name: create deployment config
  openshift_v1_deployment_config:
    name: keycloak
    namespace: '{{ namespace }}'
    labels:
      app: keycloak
      service: keycloak
    replicas: 1
    selector:
      app: keycloak
      service: keycloak
    spec_template_metadata_labels:
      app: keycloak
      service: keycloak
    containers:
    - env:
      - name: KEYCLOAK_USER
        value: '{{ ADMIN_USERNAME }}'
      - name: KEYCLOAK_PASSWORD
        value: '{{ ADMIN_PASSWORD }}'
      image: docker.io/jimmidyson/keycloak-openshift:2.5.4.Final
      name: keycloak
      ports:
      - container_port: 8080
        protocol: TCP


- name: create keycloak service
  k8s_v1_service:
    name: keycloak
    namespace: '{{ namespace }}'
    labels:
      app: keycloak
      service: keycloak
    selector:
      app: keycloak
      service: keycloak
    ports:
      - name: web
        port: 80
        target_port: 8080

- name: create keycloak route
  openshift_v1_route:
    name: keycloak
    namespace: '{{ namespace }}'
    labels:
      app: keycloak
      service: keycloak
    to_name: keycloak
    spec_port_target_port: web

- 
  name: "Retrieve route to keycloak"
  shell: "oc get routes keycloak -n '{{ namespace }}' | grep -v NAME | awk '{print $2}'"
  register: keycloak_route

-
  name: "Generate keycloak auth token"
  uri:
    url: "http://{{ keycloak_route.stdout }}/auth/realms/master/protocol/openid-connect/token"
    method: POST
    body: "client_id=admin-cli&username={{ ADMIN_USERNAME }}&password={{ ADMIN_PASSWORD }}&grant_type=password"
    validate_certs: no
  register: keycloak_auth_response
  retries: 10
  delay: 10

- 
  name: "Create {{ namespace }} realm"
  uri:
    url: "http://{{ keycloak_route.stdout }}/auth/admin/realms"
    method: POST
    body: "{\"id\": \"{{ namespace }}\", \"realm\": \"{{ namespace }}\", \"displayName\": \"{{ namespace }}\" }"
    validate_certs: no
    body_format: json
    headers:
      Authorization: "bearer {{ keycloak_auth_response.json.access_token }}"
    status_code: 201