- include_tasks: label-serviceinstance.yml

- include_tasks: provision-postgres.yml
  when: POSTGRESQL_EPHEMERAL is undefined or
        not POSTGRESQL_EPHEMERAL

- include_tasks: provision-postgres-ephemeral.yml
  when: POSTGRESQL_EPHEMERAL is defined or
        POSTGRESQL_EPHEMERAL

- include_tasks: provision-keycloak.yml
  when: SHARED_SERVICE is not defined or
        not SHARED_SERVICE

- include_tasks: configure-keycloak.yml
  vars:
    KEYCLOAK_HOST: "{{keycloak_protocol}}://{{keycloak_route.stdout}}"
    KEYCLOAK_REALM: "{{ namespace }}"
  when: SHARED_HOST is not defined or
        not SHARED_SERVICE

- include_tasks: configure-keycloak.yml
  vars:
    KEYCLOAK_HOST: "{{ SHARED_HOST }}"
    KEYCLOAK_REALM: "{{ SHARED_REALM }}"
  when:
    - SHARED_HOST is defined
    - SHARED_REALM is defined

- include_role:
    name: oc-patch-file-to-configmap
  vars:
    file_contents: "{{ dashboard_file_contents }}"
    filename: "{{ dashboard_filename }}"
    configmap: "{{ dashboards_configmap }}"
    namespace: "{{ namespace }}"
